/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: actividadturistica
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
* ✅ SCHEMA VALIDATIONS ADDED
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const actividadturistica_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "idActividad": {
        type: Number,
        required: [true, 'El ID de la actividad es obligatorio'],
        unique: true,
        min: [1, 'El ID debe ser mayor a 0']
    },
    "nombre": {
        type: String,
        required: [true, 'El nombre de la actividad es obligatorio'],
        trim: true,
        minlength: [3, 'El nombre debe tener al menos 3 caracteres'],
        maxlength: [150, 'El nombre no puede exceder 150 caracteres']
    },
    "descripcion": {
        type: String,
        trim: true,
        maxlength: [500, 'La descripción no puede exceder 500 caracteres']
    },
    "duracionHoras": {
        type: Number,
        required: [true, 'La duración es obligatoria'],
        min: [0.5, 'La duración mínima es 0.5 horas'],
        max: [24, 'La duración máxima es 24 horas']
    },
    "costo": {
        type: Number,
        required: [true, 'El costo es obligatorio'],
        min: [0, 'El costo no puede ser negativo']
    },
    "horaInicio": {
        type: Date,
        required: [true, 'La hora de inicio es obligatoria']
    },
    "horaFin": {
        type: Date,
        required: [true, 'La hora de fin es obligatoria'],
        validate: {
            validator: function(v) {
                return v > this.horaInicio;
            },
            message: 'La hora de fin debe ser posterior a la hora de inicio'
        }
    },
    "idMunicipio": {
        type: Number,
        required: [true, 'El municipio es obligatorio'],
        ref: 'municipio_Mongoose'
    }
}, {
    collection: "actividadturistica",
    timestamps: true
})

// Índices
actividadturistica_Mongoose.index({ idMunicipio: 1 });
actividadturistica_Mongoose.index({ nombre: 'text', descripcion: 'text' });
actividadturistica_Mongoose.index({ costo: 1 });

export const actividadturistica_MongooseModel = model("actividadturistica_Mongoose", actividadturistica_Mongoose);