/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: administrador
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
* ✅ SCHEMA VALIDATIONS ADDED
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const administrador_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "idAdmin": {
        type: Number,
        required: [true, 'El ID del administrador es obligatorio'],
        unique: true,
        min: [1, 'El ID debe ser mayor a 0']
    },
    "nombre": {
        type: String,
        required: [true, 'El nombre es obligatorio'],
        trim: true,
        minlength: [2, 'El nombre debe tener al menos 2 caracteres'],
        maxlength: [100, 'El nombre no puede exceder 100 caracteres']
    },
    "apellido": {
        type: String,
        required: [true, 'El apellido es obligatorio'],
        trim: true,
        minlength: [2, 'El apellido debe tener al menos 2 caracteres'],
        maxlength: [100, 'El apellido no puede exceder 100 caracteres']
    },
    "email": {
        type: String,
        required: [true, 'El email es obligatorio'],
        unique: true,
        trim: true,
        lowercase: true,
        match: [/^\S+@\S+\.\S+$/, 'Por favor ingrese un email válido']
    },
    "contraseA": {
        type: String,
        required: [true, 'La contraseña es obligatoria'],
        minlength: [8, 'La contraseña debe tener al menos 8 caracteres (mayor seguridad para admin)']
    },
    "telefono": {
        type: String,
        trim: true,
        match: [/^\+?[\d\s\-()]+$/, 'Formato de teléfono inválido']
    },
    "direccion": {
        type: String,
        trim: true,
        maxlength: [200, 'La dirección no puede exceder 200 caracteres']
    },
    "estado": {
        type: String,
        enum: {
            values: ['Activo', 'Inactivo', 'Suspendido'],
            message: '{VALUE} no es un estado válido'
        },
        default: 'Activo'
    },
    "fechaRegistro": {
        type: String,
        default: () => new Date().toISOString()
    },
    "cargo": {
        type: String,
        required: [true, 'El cargo es obligatorio'],
        enum: {
            values: ['Administrador General', 'Administrador Hotel', 'Administrador Transporte', 'Soporte'],
            message: '{VALUE} no es un cargo válido'
        }
    },
    "fechaInicio": {
        type: Date,
        required: [true, 'La fecha de inicio es obligatoria'],
        validate: {
            validator: function(v) {
                return v <= new Date();
            },
            message: 'La fecha de inicio no puede ser futura'
        }
    }
}, {
    collection: "administrador",
    timestamps: true
})

// Índices
administrador_Mongoose.index({ email: 1 });
administrador_Mongoose.index({ cargo: 1, estado: 1 });

export const administrador_MongooseModel = model("administrador_Mongoose", administrador_Mongoose);