/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: aeronave
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
* ✅ SCHEMA VALIDATIONS ADDED
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const aeronave_aerolinea_Mongoose = new Schema({
    "idAerolinea": {
        type: Number,
        required: [true, 'El ID de la aerolínea es obligatorio'],
        min: [1, 'El ID debe ser mayor a 0']
    },
    "nombre": {
        type: String,
        required: [true, 'El nombre de la aerolínea es obligatorio'],
        trim: true,
        minlength: [2, 'El nombre debe tener al menos 2 caracteres'],
        maxlength: [100, 'El nombre no puede exceder 100 caracteres']
    },
    "codigoIata": {
        type: String,
        required: [true, 'El código IATA es obligatorio'],
        trim: true,
        uppercase: true,
        match: [/^[A-Z]{2}$/, 'El código IATA debe tener 2 letras (ej: AA, CO, AV)'],
        unique: true
    },
    "paisOrigen": {
        type: String,
        required: [true, 'El país de origen es obligatorio'],
        trim: true,
        maxlength: [100, 'El país no puede exceder 100 caracteres']
    }
}, {
    collection: "aeronave_aerolinea",
    _id: false
})

export const aeronave_aerolinea_MongooseModel = model("aeronave_aerolinea_Mongoose", aeronave_aerolinea_Mongoose);