/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: aeronave
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
* ✅ SCHEMA VALIDATIONS ADDED
*/
import { aeronave_aerolinea_Mongoose } from "./aeronave_aerolinea_Mongoose.js"
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const aeronave_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "idAeronave": {
        type: Number,
        required: [true, 'El ID de la aeronave es obligatorio'],
        unique: true,
        min: [1, 'El ID debe ser mayor a 0']
    },
    "idVehiculo": {
        type: Number,
        required: [true, 'El ID del vehículo es obligatorio'],
        ref: 'vehiculo_Mongoose'
    },
    "codigoAeronave": {
        type: String,
        required: [true, 'El código de aeronave es obligatorio'],
        unique: true,
        trim: true,
        uppercase: true,
        match: [/^[A-Z0-9]{4,10}$/, 'Código de aeronave inválido (4-10 caracteres alfanuméricos)']
    },
    "modelo": {
        type: String,
        required: [true, 'El modelo es obligatorio'],
        trim: true,
        maxlength: [100, 'El modelo no puede exceder 100 caracteres']
    },
    "capacidadPasajeros": {
        type: Number,
        required: [true, 'La capacidad de pasajeros es obligatoria'],
        min: [1, 'Capacidad mínima: 1 pasajero'],
        max: [850, 'Capacidad máxima: 850 pasajeros (A380)']
    },
    "idAerolinea": {
        type: Number,
        required: [true, 'La aerolínea es obligatoria']
    },
    "aerolinea": {
        type: aeronave_aerolinea_Mongoose,
        required: [true, 'Los datos de la aerolínea son obligatorios']
    }
}, {
    collection: "aeronave",
    timestamps: true
})

// Índices
aeronave_Mongoose.index({ codigoAeronave: 1 });
aeronave_Mongoose.index({ idAerolinea: 1 });
aeronave_Mongoose.index({ idVehiculo: 1 });

export const aeronave_MongooseModel = model("aeronave_Mongoose", aeronave_Mongoose);