/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: carro
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
* ✅ SCHEMA VALIDATIONS ADDED
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const carro_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "idCarro": {
        type: Number,
        required: [true, 'El ID del carro es obligatorio'],
        unique: true,
        min: [1, 'El ID debe ser mayor a 0']
    },
    "idVehiculo": {
        type: Number,
        required: [true, 'El ID del vehículo es obligatorio'],
        ref: 'vehiculo_Mongoose'
    },
    "placa": {
        type: String,
        required: [true, 'La placa es obligatoria'],
        unique: true,
        trim: true,
        uppercase: true,
        match: [/^[A-Z]{3}\d{3}$/, 'Formato de placa inválido (ej: ABC123)']
    },
    "marca": {
        type: String,
        required: [true, 'La marca es obligatoria'],
        trim: true,
        maxlength: [50, 'La marca no puede exceder 50 caracteres']
    },
    "modelo": {
        type: String,
        required: [true, 'El modelo es obligatorio'],
        trim: true,
        maxlength: [100, 'El modelo no puede exceder 100 caracteres']
    },
    "capacidad": {
        type: Number,
        required: [true, 'La capacidad es obligatoria'],
        min: [1, 'Capacidad mínima: 1 pasajero'],
        max: [9, 'Capacidad máxima para carro: 9 pasajeros']
    },
    "estado": {
        type: String,
        enum: {
            values: ['Activo', 'Inactivo', 'Mantenimiento', 'Fuera de servicio'],
            message: '{VALUE} no es un estado válido'
        },
        default: 'Activo'
    },
    "idHotel": {
        type: Number,
        required: [true, 'El hotel es obligatorio'],
        ref: 'hotel_Mongoose'
    }
}, {
    collection: "carro",
    timestamps: true
})

// Índices
carro_Mongoose.index({ placa: 1 });
carro_Mongoose.index({ idHotel: 1 });
carro_Mongoose.index({ estado: 1 });

export const carro_MongooseModel = model("carro_Mongoose", carro_Mongoose);