/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: cliente
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
* ✅ SCHEMA VALIDATIONS ADDED
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const cliente_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "idCliente": {
        type: Number,
        required: [true, 'El ID del cliente es obligatorio'],
        unique: true,
        min: [1, 'El ID debe ser mayor a 0']
    },
    "nombre": {
        type: String,
        required: [true, 'El nombre es obligatorio'],
        trim: true,
        minlength: [2, 'El nombre debe tener al menos 2 caracteres'],
        maxlength: [100, 'El nombre no puede exceder 100 caracteres']
    },
    "apellido": {
        type: String,
        required: [true, 'El apellido es obligatorio'],
        trim: true,
        minlength: [2, 'El apellido debe tener al menos 2 caracteres'],
        maxlength: [100, 'El apellido no puede exceder 100 caracteres']
    },
    "email": {
        type: String,
        required: [true, 'El email es obligatorio'],
        unique: true,
        trim: true,
        lowercase: true,
        match: [/^\S+@\S+\.\S+$/, 'Por favor ingrese un email válido']
    },
    "contraseA": {
        type: String,
        required: [true, 'La contraseña es obligatoria'],
        minlength: [6, 'La contraseña debe tener al menos 6 caracteres']
    },
    "telefono": {
        type: String,
        trim: true,
        match: [/^\+?[\d\s\-()]+$/, 'Formato de teléfono inválido']
    },
    "direccion": {
        type: String,
        trim: true,
        maxlength: [200, 'La dirección no puede exceder 200 caracteres']
    },
    "estado": {
        type: String,
        enum: {
            values: ['Activo', 'Inactivo', 'Suspendido'],
            message: '{VALUE} no es un estado válido'
        },
        default: 'Activo'
    },
    "fechaRegistro": {
        type: String,
        default: () => new Date().toISOString()
    },
    "numeroDocumento": {
        type: String,
        required: [true, 'El número de documento es obligatorio'],
        trim: true,
        unique: true
    },
    "tipoDocumento": {
        type: String,
        required: [true, 'El tipo de documento es obligatorio'],
        enum: {
            values: ['CC', 'CE', 'Pasaporte', 'TI'],
            message: '{VALUE} no es un tipo de documento válido'
        }
    },
    "fechaNacimiento": {
        type: Date,
        required: [true, 'La fecha de nacimiento es obligatoria'],
        validate: {
            validator: function(v) {
                return v < new Date();
            },
            message: 'La fecha de nacimiento debe ser anterior a hoy'
        }
    },
    "nacionalidad": {
        type: String,
        trim: true,
        maxlength: [50, 'La nacionalidad no puede exceder 50 caracteres']
    }
}, {
    collection: "cliente",
    timestamps: true // Agrega createdAt y updatedAt automáticamente
})

// Índices adicionales para mejorar rendimiento
cliente_Mongoose.index({ email: 1 });
cliente_Mongoose.index({ numeroDocumento: 1 });
cliente_Mongoose.index({ estado: 1 });

export const cliente_MongooseModel = model("cliente_Mongoose", cliente_Mongoose);