/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: clienteViaje
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
* ✅ SCHEMA VALIDATIONS ADDED
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const clienteViaje_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "idCliente": {
        type: Number,
        required: [true, 'El cliente es obligatorio'],
        ref: 'cliente_Mongoose'
    },
    "idViaje": {
        type: Number,
        required: [true, 'El viaje es obligatorio'],
        ref: 'viaje_Mongoose'
    },
    "rolViajero": {
        type: String,
        required: [true, 'El rol del viajero es obligatorio'],
        enum: {
            values: ['Titular', 'Acompañante', 'Menor', 'Invitado'],
            message: '{VALUE} no es un rol válido'
        }
    },
    "estado": {
        type: String,
        enum: {
            values: ['Confirmado', 'Pendiente', 'Cancelado', 'Completado'],
            message: '{VALUE} no es un estado válido'
        },
        default: 'Pendiente'
    },
    "fechaParticipacion": {
        type: Date,
        default: Date.now
    }
}, {
    collection: "clienteViaje",
    timestamps: true
})

// Índices
clienteViaje_Mongoose.index({ idCliente: 1, idViaje: 1 }, { unique: true });
clienteViaje_Mongoose.index({ estado: 1 });

export const clienteViaje_MongooseModel = model("clienteViaje_Mongoose", clienteViaje_Mongoose);