/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: cuota
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
* ✅ SCHEMA VALIDATIONS ADDED
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const cuota_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "idCuota": {
        type: Number,
        required: [true, 'El ID de la cuota es obligatorio'],
        unique: true,
        min: [1, 'El ID debe ser mayor a 0']
    },
    "numeroCuota": {
        type: Number,
        required: [true, 'El número de cuota es obligatorio'],
        min: [1, 'El número de cuota debe ser al menos 1'],
        max: [60, 'El número de cuota no puede exceder 60 (5 años)']
    },
    "fechaPago": {
        type: Date,
        required: [true, 'La fecha de pago es obligatoria']
    },
    "monto": {
        type: Number,
        required: [true, 'El monto es obligatorio'],
        min: [0, 'El monto no puede ser negativo'],
        validate: {
            validator: function(v) {
                return v > 0 && Number.isFinite(v);
            },
            message: 'El monto debe ser un número válido y mayor a 0'
        }
    },
    "estado": {
        type: String,
        required: [true, 'El estado es obligatorio'],
        enum: {
            values: ['Pendiente', 'Pagada', 'Vencida', 'Cancelada'],
            message: '{VALUE} no es un estado válido'
        },
        default: 'Pendiente'
    },
    "idFactura": {
        type: Number,
        required: [true, 'La factura es obligatoria'],
        ref: 'factura_Mongoose'
    },
    "idViaje": {
        type: Number,
        required: [true, 'El viaje es obligatorio'],
        ref: 'viaje_Mongoose'
    }
}, {
    collection: "cuota",
    timestamps: true
})

// Índices
cuota_Mongoose.index({ idFactura: 1 });
cuota_Mongoose.index({ idViaje: 1 });
cuota_Mongoose.index({ estado: 1, fechaPago: 1 });
cuota_Mongoose.index({ numeroCuota: 1, idFactura: 1 }, { unique: true });

export const cuota_MongooseModel = model("cuota_Mongoose", cuota_Mongoose);