/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: factura
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
* ✅ SCHEMA VALIDATIONS ADDED
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const factura_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "idFactura": {
        type: Number,
        required: [true, 'El ID de la factura es obligatorio'],
        unique: true,
        min: [1, 'El ID debe ser mayor a 0']
    },
    "numeroFactura": {
        type: String,
        required: [true, 'El número de factura es obligatorio'],
        unique: true,
        trim: true,
        uppercase: true,
        match: [/^F-\d{4}-\d{3,}$/, 'Formato de factura inválido (ej: F-2025-001)']
    },
    "fechaEmision": {
        type: String,
        required: [true, 'La fecha de emisión es obligatoria'],
        default: () => new Date().toISOString()
    },
    "total": {
        type: Number,
        required: [true, 'El total es obligatorio'],
        min: [0, 'El total no puede ser negativo'],
        validate: {
            validator: function(v) {
                return v >= 0 && Number.isFinite(v);
            },
            message: 'El total debe ser un número válido y positivo'
        }
    },
    "metodoPago": {
        type: String,
        required: [true, 'El método de pago es obligatorio'],
        enum: {
            values: ['Tarjeta', 'Efectivo', 'Transferencia', 'PSE'],
            message: '{VALUE} no es un método de pago válido'
        }
    },
    "estado": {
        type: String,
        required: [true, 'El estado es obligatorio'],
        enum: {
            values: ['Pendiente', 'Pagada', 'Anulada', 'Vencida'],
            message: '{VALUE} no es un estado válido'
        },
        default: 'Pendiente'
    },
    "idTarjeta": {
        type: Number,
        ref: 'tarjetabancaria_Mongoose', // Referencia a tarjeta (opcional si pago es efectivo)
        validate: {
            validator: function(v) {
                // Solo requerido si método de pago es Tarjeta
                if (this.metodoPago === 'Tarjeta') {
                    return v != null && v > 0;
                }
                return true;
            },
            message: 'La tarjeta es obligatoria cuando el método de pago es Tarjeta'
        }
    }
}, {
    collection: "factura",
    timestamps: true
})

// Índices para consultas comunes
factura_Mongoose.index({ numeroFactura: 1 });
factura_Mongoose.index({ estado: 1 });
factura_Mongoose.index({ fechaEmision: -1 }); // Ordenar por fecha descendente
factura_Mongoose.index({ idTarjeta: 1 });
factura_Mongoose.index({ metodoPago: 1, estado: 1 }); // Índice compuesto

export const factura_MongooseModel = model("factura_Mongoose", factura_Mongoose);