/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: guiaActividad
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
* ✅ SCHEMA VALIDATIONS ADDED
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const guiaActividad_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "idGuia": {
        type: Number,
        required: [true, 'El guía es obligatorio'],
        ref: 'guia_Mongoose'
    },
    "idActividad": {
        type: Number,
        required: [true, 'La actividad es obligatoria'],
        ref: 'actividadturistica_Mongoose'
    },
    "fechaAsignacion": {
        type: Date,
        required: [true, 'La fecha de asignación es obligatoria'],
        default: Date.now
    },
    "horario": {
        type: Date,
        required: [true, 'El horario es obligatorio'],
        validate: {
            validator: function(v) {
                return v >= this.fechaAsignacion;
            },
            message: 'El horario debe ser posterior o igual a la fecha de asignación'
        }
    }
}, {
    collection: "guiaActividad",
    timestamps: true
})

// Índices
guiaActividad_Mongoose.index({ idGuia: 1, idActividad: 1 });
guiaActividad_Mongoose.index({ horario: 1 });

export const guiaActividad_MongooseModel = model("guiaActividad_Mongoose", guiaActividad_Mongoose);