/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: guia
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
* ✅ SCHEMA VALIDATIONS ADDED
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const guia_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "idGuia": {
        type: Number,
        required: [true, 'El ID del guía es obligatorio'],
        unique: true,
        min: [1, 'El ID debe ser mayor a 0']
    },
    "nombre": {
        type: String,
        required: [true, 'El nombre es obligatorio'],
        trim: true,
        minlength: [2, 'El nombre debe tener al menos 2 caracteres'],
        maxlength: [100, 'El nombre no puede exceder 100 caracteres']
    },
    "apellido": {
        type: String,
        required: [true, 'El apellido es obligatorio'],
        trim: true,
        minlength: [2, 'El apellido debe tener al menos 2 caracteres'],
        maxlength: [100, 'El apellido no puede exceder 100 caracteres']
    },
    "email": {
        type: String,
        required: [true, 'El email es obligatorio'],
        unique: true,
        trim: true,
        lowercase: true,
        match: [/^\S+@\S+\.\S+$/, 'Por favor ingrese un email válido']
    },
    "contraseA": {
        type: String,
        required: [true, 'La contraseña es obligatoria'],
        minlength: [6, 'La contraseña debe tener al menos 6 caracteres']
    },
    "telefono": {
        type: String,
        trim: true,
        match: [/^\+?[\d\s\-()]+$/, 'Formato de teléfono inválido']
    },
    "direccion": {
        type: String,
        trim: true,
        maxlength: [200, 'La dirección no puede exceder 200 caracteres']
    },
    "estado": {
        type: String,
        enum: {
            values: ['Activo', 'Inactivo', 'Suspendido', 'Vacaciones'],
            message: '{VALUE} no es un estado válido'
        },
        default: 'Activo'
    },
    "fechaRegistro": {
        type: String,
        default: () => new Date().toISOString()
    },
    "idioma": {
        type: String,
        required: [true, 'El idioma es obligatorio'],
        trim: true,
        maxlength: [100, 'Los idiomas no pueden exceder 100 caracteres']
    },
    "especialidad": {
        type: String,
        required: [true, 'La especialidad es obligatoria'],
        enum: {
            values: ['Naturaleza', 'Historia', 'Aventura', 'Cultural', 'Gastronómico', 'Multidisciplinario'],
            message: '{VALUE} no es una especialidad válida'
        }
    },
    "calificacionPromedio": {
        type: Number,
        default: 5.0,
        min: [0, 'La calificación mínima es 0'],
        max: [5, 'La calificación máxima es 5'],
        validate: {
            validator: function(v) {
                return v >= 0 && v <= 5;
            },
            message: 'La calificación debe estar entre 0 y 5'
        }
    }
}, {
    collection: "guia",
    timestamps: true
})

// Índices
guia_Mongoose.index({ email: 1 });
guia_Mongoose.index({ especialidad: 1, estado: 1 });
guia_Mongoose.index({ calificacionPromedio: -1 });

export const guia_MongooseModel = model("guia_Mongoose", guia_Mongoose);