/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: habitacion
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
* ✅ SCHEMA VALIDATIONS ADDED
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const habitacion_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "idHabitacion": {
        type: Number,
        required: [true, 'El ID de la habitación es obligatorio'],
        unique: true,
        min: [1, 'El ID debe ser mayor a 0']
    },
    "numero": {
        type: String,
        required: [true, 'El número de habitación es obligatorio'],
        trim: true,
        maxlength: [10, 'El número no puede exceder 10 caracteres']
    },
    "tipo": {
        type: String,
        required: [true, 'El tipo es obligatorio'],
        enum: {
            values: ['Simple', 'Doble', 'Triple', 'Suite', 'Suite Junior', 'Presidencial'],
            message: '{VALUE} no es un tipo de habitación válido'
        }
    },
    "precioNoche": {
        type: Number,
        required: [true, 'El precio por noche es obligatorio'],
        min: [0, 'El precio no puede ser negativo']
    },
    "disponibilidad": {
        type: Number,
        default: 1,
        min: [0, 'La disponibilidad no puede ser negativa'],
        max: [1, 'La disponibilidad es 0 (ocupada) o 1 (disponible)']
    },
    "capacidad": {
        type: Number,
        required: [true, 'La capacidad es obligatoria'],
        min: [1, 'Capacidad mínima: 1 persona'],
        max: [10, 'Capacidad máxima: 10 personas']
    },
    "idHotel": {
        type: Number,
        required: [true, 'El hotel es obligatorio'],
        ref: 'hotel_Mongoose'
    }
}, {
    collection: "habitacion",
    timestamps: true
})

// Índices
habitacion_Mongoose.index({ idHotel: 1 });
habitacion_Mongoose.index({ tipo: 1, disponibilidad: 1 });
habitacion_Mongoose.index({ numero: 1, idHotel: 1 }, { unique: true });

export const habitacion_MongooseModel = model("habitacion_Mongoose", habitacion_Mongoose);