/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: hotel
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
* ✅ SCHEMA VALIDATIONS ADDED
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const hotel_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "idHotel": {
        type: Number,
        required: [true, 'El ID del hotel es obligatorio'],
        unique: true,
        min: [1, 'El ID debe ser mayor a 0']
    },
    "nombre": {
        type: String,
        required: [true, 'El nombre del hotel es obligatorio'],
        trim: true,
        minlength: [3, 'El nombre debe tener al menos 3 caracteres'],
        maxlength: [150, 'El nombre no puede exceder 150 caracteres']
    },
    "direccion": {
        type: String,
        required: [true, 'La dirección es obligatoria'],
        trim: true,
        maxlength: [200, 'La dirección no puede exceder 200 caracteres']
    },
    "categoria": {
        type: Number,
        required: [true, 'La categoría es obligatoria'],
        min: [1, 'La categoría mínima es 1 estrella'],
        max: [5, 'La categoría máxima es 5 estrellas'],
        validate: {
            validator: Number.isInteger,
            message: 'La categoría debe ser un número entero'
        }
    },
    "telefono": {
        type: String,
        trim: true,
        match: [/^\+?[\d\s\-()]+$/, 'Formato de teléfono inválido']
    },
    "emailContacto": {
        type: String,
        trim: true,
        lowercase: true,
        match: [/^\S+@\S+\.\S+$/, 'Por favor ingrese un email válido']
    },
    "municipioId": {
        type: Number,
        required: [true, 'El municipio es obligatorio'],
        ref: 'municipio_Mongoose' // Referencia a la colección municipio
    },
    "idAdministrador": {
        type: Number,
        required: [true, 'El administrador es obligatorio'],
        ref: 'administrador_Mongoose' // Referencia a la colección administrador
    }
}, {
    collection: "hotel",
    timestamps: true
})

// Índices para optimizar consultas
hotel_Mongoose.index({ municipioId: 1 });
hotel_Mongoose.index({ idAdministrador: 1 });
hotel_Mongoose.index({ categoria: 1 });
hotel_Mongoose.index({ nombre: 'text' }); // Búsqueda de texto

export const hotel_MongooseModel = model("hotel_Mongoose", hotel_Mongoose);