/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: itinerariotransporte
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
* ✅ SCHEMA VALIDATIONS ADDED
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const itinerariotransporte_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "idItinerario": {
        type: Number,
        required: [true, 'El ID del itinerario es obligatorio'],
        unique: true,
        min: [1, 'El ID debe ser mayor a 0']
    },
    "orden": {
        type: Number,
        required: [true, 'El orden es obligatorio'],
        min: [1, 'El orden debe ser al menos 1']
    },
    "fechaSalida": {
        type: Date,
        required: [true, 'La fecha de salida es obligatoria']
    },
    "fechaLlegada": {
        type: Date,
        required: [true, 'La fecha de llegada es obligatoria'],
        validate: {
            validator: function(v) {
                return v > this.fechaSalida;
            },
            message: 'La fecha de llegada debe ser posterior a la fecha de salida'
        }
    },
    "idServicio": {
        type: Number,
        required: [true, 'El servicio de transporte es obligatorio'],
        ref: 'serviciotransporte_Mongoose'
    },
    "idTrayecto": {
        type: Number,
        required: [true, 'El trayecto es obligatorio'],
        ref: 'trayecto_Mongoose'
    },
    "idViaje": {
        type: Number,
        required: [true, 'El viaje es obligatorio'],
        ref: 'viaje_Mongoose'
    }
}, {
    collection: "itinerariotransporte",
    timestamps: true
})

// Índices
itinerariotransporte_Mongoose.index({ idViaje: 1, orden: 1 });
itinerariotransporte_Mongoose.index({ idServicio: 1 });
itinerariotransporte_Mongoose.index({ fechaSalida: 1, fechaLlegada: 1 });

export const itinerariotransporte_MongooseModel = model("itinerariotransporte_Mongoose", itinerariotransporte_Mongoose);