/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: municipio
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
* ✅ SCHEMA VALIDATIONS ADDED
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const municipio_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "idMunicipio": {
        type: Number,
        required: [true, 'El ID del municipio es obligatorio'],
        unique: true,
        min: [1, 'El ID debe ser mayor a 0']
    },
    "nombre": {
        type: String,
        required: [true, 'El nombre del municipio es obligatorio'],
        trim: true,
        minlength: [2, 'El nombre debe tener al menos 2 caracteres'],
        maxlength: [100, 'El nombre no puede exceder 100 caracteres']
    },
    "departamento": {
        type: String,
        required: [true, 'El departamento es obligatorio'],
        trim: true,
        maxlength: [100, 'El departamento no puede exceder 100 caracteres']
    },
    "pais": {
        type: String,
        required: [true, 'El país es obligatorio'],
        trim: true,
        maxlength: [100, 'El país no puede exceder 100 caracteres']
    },
    "descripcionTuristica": {
        type: String,
        trim: true,
        maxlength: [1000, 'La descripción no puede exceder 1000 caracteres']
    }
}, {
    collection: "municipio",
    timestamps: true
})

// Índices
municipio_Mongoose.index({ nombre: 1, departamento: 1 });
municipio_Mongoose.index({ pais: 1 });
municipio_Mongoose.index({ nombre: 'text', descripcionTuristica: 'text' });

export const municipio_MongooseModel = model("municipio_Mongoose", municipio_Mongoose);