/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: planActividad
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
* ✅ SCHEMA VALIDATIONS ADDED
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const planActividad_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "idPlan": {
        type: Number,
        required: [true, 'El plan es obligatorio'],
        ref: 'plan_Mongoose'
    },
    "idActividad": {
        type: Number,
        required: [true, 'La actividad es obligatoria'],
        ref: 'actividadturistica_Mongoose'
    },
    "orden": {
        type: Number,
        required: [true, 'El orden es obligatorio'],
        min: [1, 'El orden debe ser al menos 1']
    }
}, {
    collection: "planActividad",
    timestamps: true
})

// Índices
planActividad_Mongoose.index({ idPlan: 1, orden: 1 });
planActividad_Mongoose.index({ idPlan: 1, idActividad: 1 }, { unique: true });

export const planActividad_MongooseModel = model("planActividad_Mongoose", planActividad_Mongoose);