/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: plan
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
* ✅ SCHEMA VALIDATIONS ADDED
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const plan_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "idPlan": {
        type: Number,
        required: [true, 'El ID del plan es obligatorio'],
        unique: true,
        min: [1, 'El ID debe ser mayor a 0']
    },
    "nombre": {
        type: String,
        required: [true, 'El nombre del plan es obligatorio'],
        trim: true,
        minlength: [3, 'El nombre debe tener al menos 3 caracteres'],
        maxlength: [150, 'El nombre no puede exceder 150 caracteres']
    },
    "tipo": {
        type: String,
        required: [true, 'El tipo de plan es obligatorio'],
        enum: {
            values: ['Todo Incluido', 'Media Pensión', 'Solo Alojamiento', 'Aventura', 'Cultural', 'Relajación', 'Personalizado'],
            message: '{VALUE} no es un tipo de plan válido'
        }
    },
    "descripcion": {
        type: String,
        trim: true,
        maxlength: [1000, 'La descripción no puede exceder 1000 caracteres']
    },
    "precioTotal": {
        type: Number,
        required: [true, 'El precio total es obligatorio'],
        min: [0, 'El precio no puede ser negativo'],
        validate: {
            validator: function(v) {
                return v >= 0 && Number.isFinite(v);
            },
            message: 'El precio debe ser un número válido y positivo'
        }
    }
}, {
    collection: "plan",
    timestamps: true
})

// Índices
plan_Mongoose.index({ tipo: 1 });
plan_Mongoose.index({ precioTotal: 1 });
plan_Mongoose.index({ nombre: 'text', descripcion: 'text' });

export const plan_MongooseModel = model("plan_Mongoose", plan_Mongoose);