/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: reserva
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
* ✅ SCHEMA VALIDATIONS ADDED
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const reserva_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "idReserva": {
        type: Number,
        required: [true, 'El ID de la reserva es obligatorio'],
        unique: true,
        min: [1, 'El ID debe ser mayor a 0']
    },
    "idViaje": {
        type: Number,
        required: [true, 'El viaje es obligatorio'],
        ref: 'viaje_Mongoose'
    },
    "idHabitacion": {
        type: Number,
        required: [true, 'La habitación es obligatoria'],
        ref: 'habitacion_Mongoose'
    },
    "fechaCheckIn": {
        type: Date,
        required: [true, 'La fecha de check-in es obligatoria']
    },
    "fechaCheckOut": {
        type: Date,
        required: [true, 'La fecha de check-out es obligatoria'],
        validate: {
            validator: function(v) {
                return v > this.fechaCheckIn;
            },
            message: 'La fecha de check-out debe ser posterior al check-in'
        }
    },
    "estado": {
        type: String,
        required: [true, 'El estado es obligatorio'],
        enum: {
            values: ['Confirmada', 'Pendiente', 'Cancelada', 'Completada', 'No Show'],
            message: '{VALUE} no es un estado válido'
        },
        default: 'Pendiente'
    },
    "costoTotal": {
        type: Number,
        required: [true, 'El costo total es obligatorio'],
        min: [0, 'El costo no puede ser negativo']
    }
}, {
    collection: "reserva",
    timestamps: true
})

// Índices
reserva_Mongoose.index({ idViaje: 1 });
reserva_Mongoose.index({ idHabitacion: 1 });
reserva_Mongoose.index({ estado: 1 });
reserva_Mongoose.index({ fechaCheckIn: 1, fechaCheckOut: 1 });

export const reserva_MongooseModel = model("reserva_Mongoose", reserva_Mongoose);