/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: serviciotransporte
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
* ✅ SCHEMA VALIDATIONS ADDED
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const serviciotransporte_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "idServicio": {
        type: Number,
        required: [true, 'El ID del servicio es obligatorio'],
        unique: true,
        min: [1, 'El ID debe ser mayor a 0']
    },
    "fechaInicio": {
        type: Date,
        required: [true, 'La fecha de inicio es obligatoria']
    },
    "fechaFin": {
        type: Date,
        required: [true, 'La fecha de fin es obligatoria'],
        validate: {
            validator: function(v) {
                return v > this.fechaInicio;
            },
            message: 'La fecha de fin debe ser posterior a la fecha de inicio'
        }
    },
    "costo": {
        type: Number,
        required: [true, 'El costo es obligatorio'],
        min: [0, 'El costo no puede ser negativo']
    },
    "estado": {
        type: String,
        required: [true, 'El estado es obligatorio'],
        enum: {
            values: ['Programado', 'En curso', 'Completado', 'Cancelado', 'Retrasado'],
            message: '{VALUE} no es un estado válido'
        },
        default: 'Programado'
    },
    "idTrayecto": {
        type: Number,
        required: [true, 'El trayecto es obligatorio'],
        ref: 'trayecto_Mongoose'
    },
    "idVehiculo": {
        type: Number,
        required: [true, 'El vehículo es obligatorio'],
        ref: 'vehiculo_Mongoose'
    }
}, {
    collection: "serviciotransporte",
    timestamps: true
})

// Índices
serviciotransporte_Mongoose.index({ idTrayecto: 1 });
serviciotransporte_Mongoose.index({ idVehiculo: 1 });
serviciotransporte_Mongoose.index({ estado: 1, fechaInicio: 1 });

export const serviciotransporte_MongooseModel = model("serviciotransporte_Mongoose", serviciotransporte_Mongoose);