/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: tarjetabancaria
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
* ✅ SCHEMA VALIDATIONS ADDED (Datos sensibles - alta seguridad)
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const tarjetabancaria_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "idTarjeta": {
        type: Number,
        required: [true, 'El ID de la tarjeta es obligatorio'],
        unique: true,
        min: [1, 'El ID debe ser mayor a 0']
    },
    "tipo": {
        type: String,
        required: [true, 'El tipo de tarjeta es obligatorio'],
        enum: {
            values: ['Crédito', 'Débito'],
            message: '{VALUE} no es un tipo válido (solo Crédito o Débito)'
        }
    },
    "numeroEnmascarado": {
        type: String,
        required: [true, 'El número enmascarado es obligatorio'],
        trim: true,
        match: [/^\*{4,12}\d{4}$/, 'Formato de número enmascarado inválido (ej: ****1234)']
    },
    "nombreTitular": {
        type: String,
        required: [true, 'El nombre del titular es obligatorio'],
        trim: true,
        uppercase: true,
        minlength: [5, 'El nombre del titular debe tener al menos 5 caracteres'],
        maxlength: [100, 'El nombre no puede exceder 100 caracteres']
    },
    "fechaVencimiento": {
        type: Date,
        required: [true, 'La fecha de vencimiento es obligatoria'],
        validate: {
            validator: function(v) {
                return v > new Date();
            },
            message: 'La tarjeta está vencida o la fecha es inválida'
        }
    },
    "bancoEmisor": {
        type: String,
        required: [true, 'El banco emisor es obligatorio'],
        trim: true,
        minlength: [3, 'El nombre del banco debe tener al menos 3 caracteres'],
        maxlength: [100, 'El nombre del banco no puede exceder 100 caracteres']
    },
    "idCliente": {
        type: Number,
        required: [true, 'El cliente es obligatorio'],
        ref: 'cliente_Mongoose' // Referencia al cliente
    }
}, {
    collection: "tarjetabancaria",
    timestamps: true
})

// Índices para consultas eficientes
tarjetabancaria_Mongoose.index({ idCliente: 1 });
tarjetabancaria_Mongoose.index({ numeroEnmascarado: 1 });

// Middleware pre-save para seguridad adicional
tarjetabancaria_Mongoose.pre('save', function(next) {
    // Validar que no se guarde el número completo de tarjeta
    if (this.numeroEnmascarado && !/^\*/.test(this.numeroEnmascarado)) {
        return next(new Error('⚠️ SEGURIDAD: No se permite guardar números de tarjeta completos'));
    }
    next();
});

export const tarjetabancaria_MongooseModel = model("tarjetabancaria_Mongoose", tarjetabancaria_Mongoose);