/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: trayecto
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
* ✅ SCHEMA VALIDATIONS ADDED
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const trayecto_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "idTrayecto": {
        type: Number,
        required: [true, 'El ID del trayecto es obligatorio'],
        unique: true,
        min: [1, 'El ID debe ser mayor a 0']
    },
    "origen": {
        type: Number,
        required: [true, 'El origen es obligatorio'],
        ref: 'municipio_Mongoose'
    },
    "destino": {
        type: Number,
        required: [true, 'El destino es obligatorio'],
        ref: 'municipio_Mongoose',
        validate: {
            validator: function(v) {
                return v !== this.origen;
            },
            message: 'El destino debe ser diferente al origen'
        }
    },
    "tipoTransporte": {
        type: String,
        required: [true, 'El tipo de transporte es obligatorio'],
        enum: {
            values: ['Aéreo', 'Terrestre', 'Marítimo', 'Fluvial'],
            message: '{VALUE} no es un tipo de transporte válido'
        }
    },
    "distanciaKm": {
        type: Number,
        required: [true, 'La distancia es obligatoria'],
        min: [0, 'La distancia no puede ser negativa'],
        max: [20000, 'La distancia no puede exceder 20,000 km']
    },
    "duracionEstimada": {
        type: Date,
        required: [true, 'La duración estimada es obligatoria']
    },
    "costoBase": {
        type: Number,
        required: [true, 'El costo base es obligatorio'],
        min: [0, 'El costo no puede ser negativo']
    }
}, {
    collection: "trayecto",
    timestamps: true
})

// Índices
trayecto_Mongoose.index({ origen: 1, destino: 1 });
trayecto_Mongoose.index({ tipoTransporte: 1 });
trayecto_Mongoose.index({ distanciaKm: 1 });

export const trayecto_MongooseModel = model("trayecto_Mongoose", trayecto_Mongoose);