/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: vehiculo
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
* ✅ SCHEMA VALIDATIONS ADDED (con GPS embebido)
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

// Schema embebido para GPS (no es una colección separada)
const gpsEmbebidoSchema = new Schema({
    "latitud": {
        type: Number,
        required: [true, 'La latitud es obligatoria'],
        min: [-90, 'Latitud inválida (mín: -90)'],
        max: [90, 'Latitud inválida (máx: 90)']
    },
    "longitud": {
        type: Number,
        required: [true, 'La longitud es obligatoria'],
        min: [-180, 'Longitud inválida (mín: -180)'],
        max: [180, 'Longitud inválida (máx: 180)']
    },
    "ultimaActualizacion": {
        type: Date,
        default: Date.now
    },
    "estado": {
        type: String,
        enum: {
            values: ['Activo', 'Inactivo', 'Mantenimiento'],
            message: '{VALUE} no es un estado GPS válido'
        },
        default: 'Activo'
    }
}, { _id: false }); // No generar _id para subdocumento

export const vehiculo_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "idVehiculo": {
        type: Number,
        required: [true, 'El ID del vehículo es obligatorio'],
        unique: true,
        min: [1, 'El ID debe ser mayor a 0']
    },
    "tipo": {
        type: String,
        required: [true, 'El tipo de vehículo es obligatorio'],
        enum: {
            values: ['Bus', 'Minivan', 'Automóvil', 'Camioneta'],
            message: '{VALUE} no es un tipo de vehículo válido'
        }
    },
    "placa": {
        type: String,
        required: [true, 'La placa es obligatoria'],
        unique: true,
        trim: true,
        uppercase: true,
        match: [/^[A-Z]{3}\d{3}$/, 'Formato de placa inválido (ej: ABC123)']
    },
    "modelo": {
        type: String,
        required: [true, 'El modelo es obligatorio'],
        trim: true,
        maxlength: [100, 'El modelo no puede exceder 100 caracteres']
    },
    "capacidad": {
        type: Number,
        required: [true, 'La capacidad es obligatoria'],
        min: [1, 'Capacidad mínima: 1 pasajero'],
        max: [60, 'Capacidad máxima: 60 pasajeros']
    },
    "estado": {
        type: String,
        enum: {
            values: ['Activo', 'Inactivo', 'Mantenimiento', 'Fuera de servicio'],
            message: '{VALUE} no es un estado válido'
        },
        default: 'Activo'
    },
    "gps": {
        type: gpsEmbebidoSchema,
        required: [true, 'El GPS es obligatorio para el vehículo']
    }
}, {
    collection: "vehiculo",
    timestamps: true
})

// Índices
vehiculo_Mongoose.index({ placa: 1 });
vehiculo_Mongoose.index({ tipo: 1, estado: 1 });
vehiculo_Mongoose.index({ 'gps.estado': 1 }); // Índice en campo embebido

export const vehiculo_MongooseModel = model("vehiculo_Mongoose", vehiculo_Mongoose);