/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: vehiculo
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const vehiculo_gps_Mongoose = new Schema({
    "idGps": Number,
    "latitud": Number,
    "longitud": Number,
    "ultimaActualizacion": String,
    "estado": String,
    "idVehiculo": Number,
}, { collection: "vehiculo_gps" })

export const vehiculo_gps_MongooseModel = model("vehiculo_gps_Mongoose", vehiculo_gps_Mongoose);