/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: vehiculo_gps
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-10-19
 * ✅ SCHEMA VALIDATIONS ADDED
 */
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const vehiculo_gps_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    idGps: {
      type: Number,
      required: [true, "El ID del GPS es obligatorio"],
      unique: true,
      min: [1, "El ID debe ser mayor a 0"],
    },
    latitud: {
      type: Number,
      required: [true, "La latitud es obligatoria"],
      min: [-90, "Latitud inválida (debe estar entre -90 y 90)"],
      max: [90, "Latitud inválida (debe estar entre -90 y 90)"],
      validate: {
        validator: function (v) {
          return Number.isFinite(v);
        },
        message: "La latitud debe ser un número válido",
      },
    },
    longitud: {
      type: Number,
      required: [true, "La longitud es obligatoria"],
      min: [-180, "Longitud inválida (debe estar entre -180 y 180)"],
      max: [180, "Longitud inválida (debe estar entre -180 y 180)"],
      validate: {
        validator: function (v) {
          return Number.isFinite(v);
        },
        message: "La longitud debe ser un número válido",
      },
    },
    ultimaActualizacion: {
      type: Date,
      required: [true, "La fecha de última actualización es obligatoria"],
      default: Date.now,
      validate: {
        validator: function (v) {
          return v <= new Date();
        },
        message: "La fecha de actualización no puede ser futura",
      },
    },
    estado: {
      type: String,
      required: [true, "El estado del GPS es obligatorio"],
      enum: {
        values: ["Activo", "Inactivo", "Mantenimiento", "Fuera de servicio"],
        message: "{VALUE} no es un estado válido",
      },
      default: "Activo",
    },
    idVehiculo: {
      type: Number,
      required: [true, "El ID del vehículo es obligatorio"],
      ref: "vehiculo_Mongoose",
      min: [1, "El ID del vehículo debe ser mayor a 0"],
    },
  },
  {
    collection: "vehiculo_gps",
    timestamps: true,
  }
);

// Índices para optimizar consultas
vehiculo_gps_Mongoose.index({ idVehiculo: 1 });
vehiculo_gps_Mongoose.index({ estado: 1 });
vehiculo_gps_Mongoose.index({ ultimaActualizacion: -1 });
vehiculo_gps_Mongoose.index({ latitud: 1, longitud: 1 }); // Índice compuesto para búsquedas geográficas

export const vehiculo_gps_MongooseModel = model(
  "vehiculo_gps_Mongoose",
  vehiculo_gps_Mongoose
);
