/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: viajePlan
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
* ✅ SCHEMA VALIDATIONS ADDED
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const viajePlan_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "idViaje": {
        type: Number,
        required: [true, 'El viaje es obligatorio'],
        ref: 'viaje_Mongoose'
    },
    "idPlan": {
        type: Number,
        required: [true, 'El plan es obligatorio'],
        ref: 'plan_Mongoose'
    },
    "fechaAsignacion": {
        type: Date,
        required: [true, 'La fecha de asignación es obligatoria'],
        default: Date.now
    },
    "cantidadPersonas": {
        type: Number,
        required: [true, 'La cantidad de personas es obligatoria'],
        min: [1, 'Debe haber al menos 1 persona'],
        max: [100, 'La cantidad máxima es 100 personas por plan']
    }
}, {
    collection: "viajePlan",
    timestamps: true
})

// Índices
viajePlan_Mongoose.index({ idViaje: 1, idPlan: 1 }, { unique: true });
viajePlan_Mongoose.index({ fechaAsignacion: 1 });

export const viajePlan_MongooseModel = model("viajePlan_Mongoose", viajePlan_Mongoose);