/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: viaje
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-10-19
* ✅ SCHEMA VALIDATIONS ADDED
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const viaje_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "idViaje": {
        type: Number,
        required: [true, 'El ID del viaje es obligatorio'],
        unique: true,
        min: [1, 'El ID debe ser mayor a 0']
    },
    "nombre": {
        type: String,
        required: [true, 'El nombre del viaje es obligatorio'],
        trim: true,
        minlength: [3, 'El nombre debe tener al menos 3 caracteres'],
        maxlength: [200, 'El nombre no puede exceder 200 caracteres']
    },
    "fechaInicio": {
        type: Date,
        required: [true, 'La fecha de inicio es obligatoria']
    },
    "fechaFin": {
        type: Date,
        required: [true, 'La fecha de fin es obligatoria'],
        validate: {
            validator: function(v) {
                return v > this.fechaInicio;
            },
            message: 'La fecha de fin debe ser posterior a la fecha de inicio'
        }
    },
    "costoTotal": {
        type: Number,
        required: [true, 'El costo total es obligatorio'],
        min: [0, 'El costo no puede ser negativo'],
        validate: {
            validator: function(v) {
                return v >= 0 && Number.isFinite(v);
            },
            message: 'El costo debe ser un número válido y positivo'
        }
    },
    "estado": {
        type: String,
        required: [true, 'El estado es obligatorio'],
        enum: {
            values: ['Programado', 'En curso', 'Completado', 'Cancelado', 'Pospuesto'],
            message: '{VALUE} no es un estado válido'
        },
        default: 'Programado'
    }
}, {
    collection: "viaje",
    timestamps: true
})

// Índices
viaje_Mongoose.index({ estado: 1 });
viaje_Mongoose.index({ fechaInicio: 1, fechaFin: 1 });
viaje_Mongoose.index({ nombre: 'text' });

// Middleware para calcular duración
viaje_Mongoose.virtual('duracionDias').get(function() {
    if (this.fechaInicio && this.fechaFin) {
        const diff = this.fechaFin - this.fechaInicio;
        return Math.ceil(diff / (1000 * 60 * 60 * 24));
    }
    return 0;
});

export const viaje_MongooseModel = model("viaje_Mongoose", viaje_Mongoose);